### ISSUE TITLE
Não precisa consultar o ViaCEP

### ISSUE THREAD

**Issue by leocavalcante** [samucca/latitude-e-longitude-pelo-cep#2]
Você pode mandar o CEP direto pra API do Gmaps:
https://maps.googleapis.com/maps/api/geocode/json?address=01311-300&components=country:BR

**Comment by samucca** [comment]
dessa forma, eu nao consigo apontar precisamente, na residencia por exemplo

**Comment by leocavalcante** [comment]
Mas você não faz isso atualmente 🤔

**Comment by samucca** [comment]
a api pelo cep, nao consigo inserir o numero, e aque estou usando eu passo endereço com numero.
ai retorna tranquilo, e mais codigo, porem mais preciso a localização, minha ideia e quando a pessoa for cadastrar eu pegar esse valor exato, pra salvar em um banco,

**Comment by leocavalcante** [comment]
Entendi, foi mal.
Agora vi o número fazendo parte do processo.

2017-02-21 18:02 GMT-03:00 Samucca <notifications@github.com>:

**Comment by samucca** [comment]
rsrsrsrs magina cara, valew pela dica nao sabia que dava para consultar pelo cep :) precisando tamos ai abs
